// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { memoryStorage } from './memoryStorage';
import { isDemoMode } from '@/lib/appMode';

const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const hasConfiguredSupabase = Boolean(envUrl && envKey);

const SUPABASE_URL = envUrl || 'https://demo.local';
const SUPABASE_PUBLISHABLE_KEY = envKey || 'demo-anon-key';

if (!hasConfiguredSupabase && !isDemoMode && typeof window !== 'undefined') {
  console.warn(
    '[Supabase] Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. ' +
      'Running with a placeholder client; network features will be unavailable.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Auth tokens are stored in memory only (not localStorage) to limit XSS impact.
 * Tradeoff: user is logged out on tab close or refresh. For short-lived JWTs
 * and refresh rotation, configure JWT expiry in Supabase Dashboard → Auth → Settings.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: memoryStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
